### PR TITLE
Fix for #91

### LINKED ISSUE #91: baseDir does not appear to be applied consistently
Ben, first of all, thanks so much for a great plugin! Much better than the other cache-bust plugins I have found.

I'm having trouble getting baseDir to work. None of the assets in the css file are being found. Here's the setup:

* current dir contains Gruntfile.js
* dist/ folder (subdir of current) contains all the public content ready to be cache busted. Everything in that folder is relative to that folder (it basically just gets copied to an html folder on a web server). All filenames are relative to index.html and none are absolute (i.e. the whole thing would work from the root of a domain or from a subdir of a domain).

Gruntfile.js

    	options: {
    		encoding: 'utf8',
    		algorithm: 'sha256',
    		length: 16,
    		baseDir: "dist/",
    		jsonOutput: 'rename-cachebuster-map.json',
    		deleteOriginals: true,
    		enableUrlFragmentHint: true,
    	},
    	assets: {
    		files: [{
    			src: [
    			      'dist/js/combined.js',
    			      'dist/index.html',
    			      'dist/css/combined*.css',
    			      ]
    		}]
    	},

If I don't specify dist/ in front of the src files it doesn't find them.
However, the stuff in the css file is not found, e.g. lots of messages like this while processing css:
`>> Static asset "images\bg-video.jpg" skipped because it wasn't found.`

And the json output:

    {
      "dist\\images\\twitter-share.png": "images\/twitter-share.b60dd3dc7e98c7ca.png",
      "dist\\images\\facebook-share.png": "images\/facebook-share.74bcb41d47f3adb0.png",
      "dist\\faq.html": "faq.9cc576831abdd69a.html",
      "dist\\team.html": "team.9b8d5c53ac8c7bd0.html",
      "dist\\js\\combined.js": "js\/combined.740066ba6ac91af5.js",
      "dist\\css\\combined.css": "css\/combined.32469c2f0ebe0f31.css",
      etc.
    }

Note the dist/ for the original and missing for the busted. Also note the mixing of forward slashes and backslashes (but I don't think that's the issue).

It would also be nice if the baseDir were auto-applied in front of the asset filenames (so it did not need to be repeated) and did not appear at all in the map json (because it doesn't relate to the distribution package at all). In other words, just prepend baseDir to all file accesses but otherwise don't use it anywhere. Does that make sense?

Is my config broken or have I run into a use case that needs a little more debugging?

Thanks for any tips!
Mike

### PR DESCRIPTION
**Pull request by mbenna**
I'm now pretty comfortable that this fixes #91. I've added some test cases which fail before the fix and pass after the fix. There's commentary in the code around the fix; it should be removed once the fix is approved.

I also ran into a test failure I can't explain and I believe is unrelated to this path fix, but it needs a review to know for sure:

        //TODO: THIS TEST FAILS FOR UNKNOWN REASONS! IT PRODUCES THIS:
        //background-image: url('../assets/image1?4eee70fda47d1478.4eee70fda47d1478.jpg');
        //test.ok(srcset.match(/assets\/css-image1.[a-z0-9]{16}\.jpg/), 'testing the replacement of an image when css in a different subdir than asset');

### CODE REVIEW

**Comment by mbenna** [comment]
Ben, I've merged all the recent master commits into this fork and removed all conflicts. It's ready for review & merge now. If there are problems, please let me know. - Mike

**Comment by hollandben** [comment]
Hi Mike,

Thanks for the PR and keeping it up to date as I keep changing things (sorry). There's a few things that worry me so I will leave comments next to the sections of code instead of here.

File: Gruntfile.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ module.exports = function(grunt) {
                 files: [{
                     expand: true,
                     cwd: 'tmp/',
-                    src: ['*.html', '*.css', '!replace*.*', '!*.php', '!cdnPath.html']
+                    src: ['*.html', '*.css', '!replace*.*', '!*.php', '!cdnPath.html', 'css/*.css']
```
Comment (hollandben) [inline Gruntfile.js]: No need to add the `css/*.css` glob here as it's in the `rename` task and that is what your tests are covering

File: tasks/cachebust.js [hunk 2]
```diff
@@ -67,7 +67,10 @@ module.exports = function(grunt) {
             var isCSS = (/\.css$/).test(filepath);
 
             findStaticAssets(markup, isCSS).forEach(function(reference) {
-                var filePath = (opts.baseDir ? opts.baseDir : path.dirname(filepath)) + '/';
+                // original code (doesn't handle css in a subdirectory with relative paths to assets):
+                // var filePath = (opts.baseDir ? opts.baseDir : path.dirname(filepath)) + '/';
+                // simpler new code. filepath already includes opts.baseDir so no need to check again:
+                var filePath = path.dirname(filepath) + '/';
```
Comment (hollandben) [inline tasks/cachebust.js]: This is the bit that worries me most. It made me aware that there is currently no test checking that the `baseDir` option is applied correctly. I've created a test that does just that over at #106. I have a feeling once you've updated this branch with that change it will start failing. I'll grab a copy of your branch and have a play around as well.

I've tried to avoid supporting relative paths in files because it's a bit of an annoyance really. It's always safer to give it a relative path from the root.

Comment (hollandben) [inline tasks/cachebust.js]: Just realised I didn't add the test to #106 - woops!! Will do it now (tiredness)

Comment (hollandben) [inline tasks/cachebust.js]: Added here - https://github.com/hollandben/grunt-cache-bust/commit/7e9e2a94516f4ae47f999b44e5310986cbbbbc70#diff-cf92aad3303fd0f38a0a3f2093fdcf3aR1

**Comment by hollandben** [comment]
I've taken the above and fixed the tests in the comment above. You can find it at #108. If you are happy with it, I can get it merged and close this one.
